# Jetty
server.port=8080
application.name=fplos

# Auditlogger
auditlogger.vendor=Foreldrepenger
auditlogger.product=fplos

# Kafka / AIven
kafka.behandlinghendelse.topic=teamforeldrepenger.behandling-hendelse-v1
